### ISSUE TITLE
gUncaught Error: spawn E2BIG

### ISSUE THREAD

**Issue by jachiike-madubuko** [UltCombo/ult-terminal#18]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.33.1 x64
**Electron**: 2.0.16
**OS**: Mac OS X 10.14.1
**Thrown From**: [ult-terminal](https://github.com/UltCombo/ult-terminal) package 0.2.2

### Stack Trace

Uncaught Error: spawn E2BIG

```
At internal/child_process.js:323

Error: spawn E2BIG
    at _errnoException (util.js:1024:11)
    at ChildProcess.spawn (internal/child_process.js:323:11)
    at exports.spawn (child_process.js:514:9)
    at Object.exports.execFile (child_process.js:224:15)
    at Object.module.(anonymous function) [as execFile] (ELECTRON_ASAR.js:193:20)
    at exports.exec (child_process.js:154:18)
    at ELECTRON_ASAR.js:721:23
    at TermView.module.exports.TermView.spawn (/packages/ult-terminal/lib/term-view.coffee:315:16)
    at TermView.module.exports.TermView.readLine (/packages/ult-terminal/lib/term-view.coffee:105:6)
    at StatusView.module.exports.StatusView.runActiveTermCommand (/packages/ult-terminal/lib/status-view.coffee:71:31)
    at /packages/ult-terminal/lib/status-view.coffee:26:76)
    at CommandRegistry.handleCommandEvent (/private/var/folders/wh/5m1t1yb10j3bb_c1670m8hbw0000gn/T/AppTranslocation/EA8E3319-04AF-401B-A11A-D4BC089BA48A/d/Atom.app/Contents/Resources/app/static/<embedded>:11:350034)
    at KeymapManager.t.exports.KeymapManager.dispatchCommandEvent (/private/var/folders/wh/5m1t1yb10j3bb_c1670m8hbw0000gn/T/AppTranslocation/EA8E3319-04AF-401B-A11A-D4BC089BA48A/d/Atom.app/Contents/Resources/app/static/<embedded>:11:1231386)
    at KeymapManager.t.exports.KeymapManager.handleKeyboardEvent (/private/var/folders/wh/5m1t1yb10j3bb_c1670m8hbw0000gn/T/AppTranslocation/EA8E3319-04AF-401B-A11A-D4BC089BA48A/d/Atom.app/Contents/Resources/app/static/<embedded>:11:1227520)
    at WindowEventHandler.handleDocumentKeyEvent (/private/var/folders/wh/5m1t1yb10j3bb_c1670m8hbw0000gn/T/AppTranslocation/EA8E3319-04AF-401B-A11A-D4BC089BA48A/d/Atom.app/Contents/Resources/app/static/<embedded>:11:285213)
```

### Commands

```
     -6:16.1.0 core:confirm (input.hidden-input)
 57x -6:05.0 core:move-left (input.hidden-input)
  4x -5:59.7.0 core:move-right (input.hidden-input)
  6x -5:57.9.0 core:backspace (input.hidden-input)
     -5:48.4.0 core:confirm (input.hidden-input)
 28x -5:16.1.0 core:move-left (input.hidden-input)
  2x -5:12.1.0 core:confirm (input.hidden-input)
     -4:00.1.0 find-and-replace:show (input.hidden-input)
     -3:57.5.0 core:backspace (input.hidden-input)
 40x -3:55.8.0 core:confirm (input.hidden-input)
  3x -3:27.7.0 core:backspace (input.hidden-input)
 17x -2:49.6.0 core:confirm (input.hidden-input)
 36x -1:50 core:undo (div.tool-panel.tree-view)
     -1:40 core:copy (input.hidden-input)
     -0:24.8.0 core:paste (input.hidden-input)
     -0:11.7.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-json-editor 0.4.1 
autocomplete-json 5.5.2 
Hydrogen 2.7.0 
moonlight 0.11.0 
rocket-dark-syntax 1.0.0 
teletype 0.13.3 
ult-terminal 0.2.2 
```

**Comment by UltCombo** [comment]
Looks like one of your commands has too many arguments or an argument that's too big. I don't think this can be fixed in the plugin as it is a system limitation.

That said, I've switched to VS Code about two years ago and don't intend to actively maintain Atom extensions anymore. I'd recommend to look for a more up-to-date plugin or fork it.

**Comment by UltCombo** [comment]
Closed as the error originates from system limitation, not plugin code.
